// GENERATED — DO NOT EDIT.
// Tork PII country registry, bundle version 1.2.0 (content cfd4f61ebaf4).
// Source: landing/lib/pii/registry/ via scripts/pii/generate-sdk-registry.ts.
// Regenerate:  npx tsx scripts/pii/generate-sdk-registry.ts
// See generated/sdk-registry/README.md for the rules this data is fed to.

using System.Collections.Generic;

namespace Tork.Governance.Pii
{
    public sealed record PiiPattern(
        string Name, string Country, string Kind, string Regex,
        string Redaction, string Type, string Label, bool RequiresKeyword,
        bool AlwaysOn, string[] Keywords, string[] WholeWordKeywords, string[] NearMissKeywords,
        bool NearMissFallback, string? Checksum, bool ChecksumRequired);

    public sealed record PiiSignal(
        string Country, string Regex, string Flags,
        string[] Keywords, string[] WholeWordKeywords, string Activates);

    public sealed record PiiCountry(
        string Code, string Name, string CallingCode, bool Bloc, string[] Patterns);

    public static class PiiRegistry
    {
        public const string Version = "1.2.0";
        public const string ContentHash = "cfd4f61ebaf45e743ba20d995d5ed585dd284778a2b3202ba917d71164b4fa26";

        // The keyword gate is ASYMMETRIC — see README.md, rule 3.
        public const int KeywordWindowBefore = 60;
        public const int KeywordWindowAfter = 40;
        public const int ContextWindow = 60;
        public const int LabelWindow = 60;
        public const int LabelReach = 25;

        public const string NearMissRedaction = "[NATIONAL_ID_REDACTED]";
        public const string NearMissType = "national_id_near_miss";
        public static readonly string[] NearMissKinds = new string[] { "health_id", "national_id", "tax_id" };

        public static readonly string[] TableDelimiters = new string[] { "\t", "|", ";", "," };
        public const int TableMaxHeaderLength = 32;
        public const int TableMaxHeaderWords = 4;
        public const int TableMinRows = 3;
        public const int TableMinCommaColumns = 3;

        public static readonly string[] Labels = new string[]
        {
            "AADHAAR",
            "ABN",
            "ACN",
            "BVN",
            "CA_PASSPORT",
            "CA_PHONE",
            "CA_POSTAL",
            "CNIC",
            "CNPJ",
            "CODICE_FISCALE",
            "CPF",
            "EMIRATES_ID",
            "GHANA_CARD",
            "IFSC",
            "ITIN",
            "KRA_PIN",
            "MEDICARE",
            "MYKAD",
            "MY_NUMBER",
            "NATIONAL_ID",
            "NHS",
            "NIK",
            "NIN",
            "NINO",
            "NRIC",
            "PAN",
            "PASSPORT",
            "PHONE",
            "PINCODE",
            "PO_BOX",
            "RESIDENT_ID",
            "RFC",
            "RRN",
            "SIN",
            "SORT_CODE",
            "TAN",
            "TAX_ID",
            "TFN",
            "UK_POSTCODE",
            "ZA_ID",
        };

        public static readonly string[] ReferenceLabels = new string[]
        {
            "order",
            "invoice",
            "purchase order",
            "po no",
            "po number",
            "job number",
            "job no",
            "booking",
            "tracking",
            "consignment",
            "waybill",
            "airway bill",
            "awb",
            "docket",
            "quote",
            "quotation",
            "ticket",
            "receipt",
            "serial number",
            "asset tag",
            "part number",
            "stock code",
            "batch",
            "shipment",
            "dispatch note",
            "delivery note",
            "work order",
            "contract number",
            "policy number",
            "meter number",
            "case id",
            "bestelling",
            "bestelnommer",
            "faktuur",
            "kwotasie",
            "commande",
            "facture",
            "devis",
            "bon de livraison",
            "expédition",
            "expedition",
            "pedido",
            "fatura",
            "factura",
            "orçamento",
            "orcamento",
            "presupuesto",
            "remito",
            "pesanan",
            "nombor pesanan",
            "invois",
            "sebut harga",
            "penghantaran",
            "resit",
            "आदेश",
            "क्रय आदेश",
            "चालान",
            "कोटेशन",
            "रसीद",
            "آرڈر",
            "انوائس",
            "رسید",
            "کوٹیشن",
            "ترسیل",
            "طلب",
            "أمر شراء",
            "فاتورة",
            "عرض سعر",
            "إيصال",
            "شحنة",
            "بوليصة",
            "注文",
            "注文番号",
            "発注",
            "発注番号",
            "請求書",
            "請求番号",
            "伝票",
            "伝票番号",
            "見積",
            "見積番号",
            "管理番号",
            "在庫番号",
            "受注",
            "出荷",
            "订单",
            "訂單",
            "订单编号",
            "訂單編號",
            "发票",
            "發票",
            "采购",
            "採購",
            "报价",
            "報價",
            "运单",
            "運單",
            "物料编号",
            "物料編號",
            "库存",
            "庫存",
            "주문",
            "주문번호",
            "구매주문",
            "송장",
            "견적",
            "견적서",
            "운송장",
            "자재번호",
            "재고번호",
            "ใบสั่งซื้อ",
            "เลขที่ใบสั่งซื้อ",
            "ใบแจ้งหนี้",
            "ใบเสนอราคา",
            "ใบส่งของ",
            "รหัสพัสดุ",
            "ใบงาน",
        };

        public static readonly string[] GenericIdKeywords = new string[]
        {
            "national id",
            "national identity",
            "national identification",
            "national number",
            "national code",
            "identity number",
            "identification number",
            "id number",
            "citizen id",
            "citizen number",
            "resident id",
            "resident number",
            "civil id",
            "civil number",
            "civil registration",
            "personal number",
            "personal identity",
            "personal code",
            "personal id",
            "tax identification",
            "tax reference",
            "taxpayer number",
            "taxpayer id",
        };

        public static readonly string[] LocalIdKeywords = new string[]
        {
            "cedula",
            "cédula",
            "iqama",
            "nadra",
            "cnic",
            "aadhaar",
            "voen",
            "vöen",
            "егн",
            "oib",
            "cpr-nummer",
            "cpr nummer",
            "kennitala",
            "personnummer",
            "adoazonosito",
            "adóazonosító",
            "szemelyi azonosito",
            "személyi azonosító",
            "kimlik",
            "рнокпп",
            "nid number",
            "sars income tax",
        };

        public static readonly IReadOnlyList<PiiCountry> Countries = new PiiCountry[]
        {
            new("AU", "Australia", "61", false, new string[] { "au_tfn", "au_abn", "au_medicare", "au_acn", "au_phone_intl" }),
            new("US", "United States", "1", false, new string[] { "us_itin", "us_passport_alpha" }),
            new("GB", "United Kingdom", "44", false, new string[] { "uk_phone_full", "uk_sort_code", "uk_nino", "uk_nhs", "uk_postcode" }),
            new("EU", "European Union", "", true, new string[] { "de_tax_id" }),
            new("AE", "United Arab Emirates", "971", false, new string[] { "emirates_id", "uae_phone", "uae_landline", "po_box" }),
            new("SA", "Saudi Arabia", "966", false, new string[] { "sa_national_id", "sa_phone" }),
            new("NG", "Nigeria", "234", false, new string[] { "ng_nin", "ng_bvn", "ng_phone" }),
            new("IN", "India", "91", false, new string[] { "in_aadhaar", "in_pan", "in_phone", "in_ifsc", "in_pincode" }),
            new("JP", "Japan", "81", false, new string[] { "jp_my_number", "jp_phone_intl", "jp_phone_national" }),
            new("CN", "China", "86", false, new string[] { "cn_resident_id", "cn_phone_intl", "cn_phone_national" }),
            new("KR", "South Korea", "82", false, new string[] { "kr_rrn", "kr_phone_intl", "kr_phone_national" }),
            new("BR", "Brazil", "55", false, new string[] { "br_cpf", "br_cnpj" }),
            new("CA", "Canada", "1", false, new string[] { "ca_sin", "ca_phone", "ca_postal_code", "ca_passport" }),
            new("ZA", "South Africa", "27", false, new string[] { "za_id_number", "za_phone" }),
            new("GH", "Ghana", "233", false, new string[] { "gh_ghana_card" }),
            new("IT", "Italy", "39", false, new string[] { "it_codice_fiscale" }),
            new("KE", "Kenya", "254", false, new string[] { "ke_kra_pin" }),
            new("MU", "Mauritius", "230", false, new string[] { "mu_tan" }),
            new("MX", "Mexico", "52", false, new string[] { "mx_rfc" }),
            new("MY", "Malaysia", "60", false, new string[] { "my_mykad" }),
            new("PK", "Pakistan", "92", false, new string[] { "pk_cnic" }),
            new("SG", "Singapore", "65", false, new string[] { "sg_nric" }),
            new("TH", "Thailand", "66", false, new string[] { "th_national_id" }),
            new("ID", "Indonesia", "62", false, new string[] { "id_nik" }),
        };

        public static readonly IReadOnlyList<PiiPattern> Patterns = new PiiPattern[]
        {
            new("au_tfn", "AU", "tax_id",
                @"\b\d{3}[ \t]?\d{3}[ \t]?\d{3}\b",
                "[TFN_REDACTED]", "au_tfn", "TFN", true,
                true,
                new string[] { "tfn", "tax file", "tax number" },
                new string[] {  },
                new string[] {  },
                true, "au_tfn", true),
            new("au_abn", "AU", "company",
                @"\b\d{2}[ \t]?\d{3}[ \t]?\d{3}[ \t]?\d{3}\b",
                "[ABN_REDACTED]", "au_abn", "ABN", true,
                true,
                new string[] { "abn", "business number", "australian business" },
                new string[] {  },
                new string[] {  },
                false, "au_abn", true),
            new("au_medicare", "AU", "health_id",
                @"\b\d{4}[ \t]?\d{5}[ \t]?\d{1}\b",
                "[MEDICARE_REDACTED]", "au_medicare", "MEDICARE", true,
                true,
                new string[] { "medicare" },
                new string[] {  },
                new string[] {  },
                false, "au_medicare", false),
            new("au_acn", "AU", "company",
                @"\b\d{3}[ \t]?\d{3}[ \t]?\d{3}\b",
                "[ACN_REDACTED]", "au_acn", "ACN", true,
                false,
                new string[] { "acn", "company number", "australian company" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("au_phone_intl", "AU", "phone",
                @"\+61[ \t]?[2-478](?:[ \t]?\d){8}\b",
                "[PHONE_REDACTED]", "au_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("us_itin", "US", "tax_id",
                @"\b9\d{2}-[7-9]\d-\d{4}\b",
                "[ITIN_REDACTED]", "us_itin", "ITIN", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("us_passport_alpha", "US", "passport",
                @"\b[A-Z]\d{8}\b",
                "[PASSPORT_REDACTED]", "us_passport", "PASSPORT", true,
                false,
                new string[] { "passport" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("uk_phone_full", "GB", "phone",
                @"(?:\+44[ \t]?|\b0)(?:7\d{3}|\d{2,4})[ \t]?\d{3,4}[ \t]?\d{3,4}\b",
                "[PHONE_REDACTED]", "uk_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("uk_sort_code", "GB", "bank",
                @"\b\d{2}-\d{2}-\d{2}\b",
                "[SORT_CODE_REDACTED]", "uk_sort_code", "SORT_CODE", true,
                false,
                new string[] { "sort code", "sort-code", "bank", "account" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("uk_nino", "GB", "national_id",
                @"\b[A-Z]{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?[A-D]\b",
                "[NINO_REDACTED]", "national_id", "NINO", true,
                false,
                new string[] { "national insurance", "ni number", "nino", "ni:", "insurance number" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("uk_nhs", "GB", "health_id",
                @"\b\d{3}[ \t]?\d{3}[ \t]?\d{4}\b",
                "[NHS_REDACTED]", "health_id", "NHS", true,
                false,
                new string[] { "nhs", "national health", "nhs number", "health service" },
                new string[] {  },
                new string[] {  },
                true, "uk_nhs", true),
            new("uk_postcode", "GB", "postcode",
                @"\b[A-Z]{1,2}\d[A-Z\d]?[ \t]?\d[A-Z]{2}\b",
                "[UK_POSTCODE_REDACTED]", "postal_code", "UK_POSTCODE", true,
                false,
                new string[] { "postcode", "post code", "uk", "united kingdom", "britain", "england", "scotland", "wales" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("de_tax_id", "EU", "tax_id",
                @"\b\d{2}[ \t]?\d{3}[ \t]?\d{3}[ \t]?\d{3}\b",
                "[TAX_ID_REDACTED]", "de_tax_id", "TAX_ID", true,
                false,
                new string[] { "steuer", "tax id", "steuernummer", "idnr", "steueridentifikation" },
                new string[] {  },
                new string[] {  },
                false, "de_steuer_id", false),
            new("emirates_id", "AE", "national_id",
                @"\b784-?\d{4}-?\d{7}-?\d\b",
                "[EMIRATES_ID_REDACTED]", "emirates_id", "EMIRATES_ID", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, "ae_emirates_id", false),
            new("uae_phone", "AE", "phone",
                @"(?:\+971[ \t]?|\b0)5[0-9][ \t]?\d{3}[ \t]?\d{4}\b",
                "[PHONE_REDACTED]", "uae_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("uae_landline", "AE", "phone",
                @"(?:\+971[ \t]?|\b0)[2-4679][ \t]?\d{3}[ \t]?\d{4}\b",
                "[PHONE_REDACTED]", "uae_landline", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("po_box", "AE", "postcode",
                @"\b[Pp]\.?[Oo]\.?[ \t]*[Bb]ox[ \t]+\d{3,6}\b",
                "[PO_BOX_REDACTED]", "po_box", "PO_BOX", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("sa_national_id", "SA", "national_id",
                @"\b[12]\d{9}\b",
                "[NATIONAL_ID_REDACTED]", "sa_national_id", "NATIONAL_ID", true,
                false,
                new string[] { "national id", "iqama", "national identification", "resident id", "saudi id" },
                new string[] {  },
                new string[] {  },
                false, "sa_national_id", false),
            new("sa_phone", "SA", "phone",
                @"(?:\+966[ \t]?|\b0)5[0-9][ \t]?\d{3}[ \t]?\d{4}\b",
                "[PHONE_REDACTED]", "sa_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("ng_nin", "NG", "national_id",
                @"\b\d{11}\b",
                "[NIN_REDACTED]", "ng_nin", "NIN", true,
                false,
                new string[] { "nin", "national id", "national identification" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("ng_bvn", "NG", "bank",
                @"\b\d{11}\b",
                "[BVN_REDACTED]", "ng_bvn", "BVN", true,
                false,
                new string[] { "bvn", "bank verification" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("ng_phone", "NG", "phone",
                @"(?:\+234[ \t]?|\b0)[789]0[1-9][ \t]?\d{3}[ \t]?\d{4}\b",
                "[PHONE_REDACTED]", "ng_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("in_aadhaar", "IN", "national_id",
                @"\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b",
                "[AADHAAR_REDACTED]", "in_aadhaar", "AADHAAR", true,
                false,
                new string[] { "aadhaar", "aadhar", "uid", "unique identification", "aadhaar number" },
                new string[] {  },
                new string[] {  },
                true, "verhoeff", true),
            new("in_pan", "IN", "tax_id",
                @"\b[A-Z]{5}\d{4}[A-Z]\b",
                "[PAN_REDACTED]", "in_pan", "PAN", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("in_phone", "IN", "phone",
                @"(?:\+91[ \t]?|\b0|\b)[6-9]\d{4}[ \t]?\d{5}\b",
                "[PHONE_REDACTED]", "in_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("in_ifsc", "IN", "bank",
                @"\b[A-Z]{4}0[A-Z0-9]{6}\b",
                "[IFSC_REDACTED]", "in_ifsc", "IFSC", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("in_pincode", "IN", "postcode",
                @"\b[1-9]\d{5}\b",
                "[PINCODE_REDACTED]", "in_pincode", "PINCODE", true,
                false,
                new string[] { "pin code", "pincode", "postal code", "zip", "address" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("jp_my_number", "JP", "national_id",
                @"\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b",
                "[MY_NUMBER_REDACTED]", "jp_my_number", "MY_NUMBER", true,
                false,
                new string[] { "my number", "individual number", "マイナンバー" },
                new string[] {  },
                new string[] {  },
                true, "jp_my_number", true),
            new("jp_phone_intl", "JP", "phone",
                @"\+81[ \t-]?[0-9]{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b",
                "[PHONE_REDACTED]", "jp_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("jp_phone_national", "JP", "phone",
                @"\b0[0-9]{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b",
                "[PHONE_REDACTED]", "jp_phone", "PHONE", true,
                false,
                new string[] { "phone", "telephone", "tel", "mobile", "cell", "fax", "call", "contact", "whatsapp", "hotline", "landline", "電話", "電話番号", "携帯", "携帯番号", "でんわ", "电话", "手机", "手機", "전화", "휴대", "휴대폰", "연락처" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("cn_resident_id", "CN", "national_id",
                @"\b\d{6}(?:19|20)\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])\d{3}[0-9Xx]\b",
                "[RESIDENT_ID_REDACTED]", "cn_resident_id", "RESIDENT_ID", true,
                false,
                new string[] { "resident id", "resident identity", "identity card", "id card", "national id", "id number", "id no", "id:", "id =", "identity number", "hukou", "身份证", "身份證", "居民身份证", "居民身份證" },
                new string[] {  },
                new string[] {  },
                true, "cn_resident_id", true),
            new("cn_phone_intl", "CN", "phone",
                @"\+86[ \t-]?1[3-9]\d{9}\b",
                "[PHONE_REDACTED]", "cn_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("cn_phone_national", "CN", "phone",
                @"\b1[3-9]\d{9}\b",
                "[PHONE_REDACTED]", "cn_phone", "PHONE", true,
                false,
                new string[] { "phone", "telephone", "tel", "mobile", "cell", "fax", "call", "contact", "whatsapp", "hotline", "landline", "電話", "電話番号", "携帯", "携帯番号", "でんわ", "电话", "手机", "手機", "전화", "휴대", "휴대폰", "연락처" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("kr_rrn", "KR", "national_id",
                @"\b\d{6}-?[1-4]\d{6}\b",
                "[RRN_REDACTED]", "kr_rrn", "RRN", true,
                false,
                new string[] { "resident registration", "resident number", "registration number", "rrn", "jumin", "juminbeonho", "national id", "id number", "id no", "id:", "id =", "identity number", "주민등록번호", "주민번호" },
                new string[] {  },
                new string[] {  },
                false, "kr_rrn", false),
            new("kr_phone_intl", "KR", "phone",
                @"\+82[ \t-]?1[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b",
                "[PHONE_REDACTED]", "kr_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("kr_phone_national", "KR", "phone",
                @"\b01[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b",
                "[PHONE_REDACTED]", "kr_phone", "PHONE", true,
                false,
                new string[] { "phone", "telephone", "tel", "mobile", "cell", "fax", "call", "contact", "whatsapp", "hotline", "landline", "電話", "電話番号", "携帯", "携帯番号", "でんわ", "电话", "手机", "手機", "전화", "휴대", "휴대폰", "연락처" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("br_cpf", "BR", "national_id",
                @"\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b",
                "[CPF_REDACTED]", "br_cpf", "CPF", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] { "cpf", "cadastro de pessoas", "receita federal" },
                true, "br_cpf", true),
            new("br_cnpj", "BR", "company",
                @"\b\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2}\b",
                "[CNPJ_REDACTED]", "br_cnpj", "CNPJ", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, "br_cnpj", true),
            new("ca_sin", "CA", "national_id",
                @"\b\d{3}[- \t]\d{3}[- \t]\d{3}\b",
                "[SIN_REDACTED]", "ca_sin", "SIN", false,
                false,
                new string[] { "sin", "social insurance", "canada revenue", "cra", "employment insurance" },
                new string[] {  },
                new string[] {  },
                false, "ca_sin", false),
            new("ca_phone", "CA", "phone",
                @"\b(\+?1[-. \t]?)?\(?\d{3}\)?[-. \t]\d{3}[-. \t]\d{4}\b",
                "[CA_PHONE_REDACTED]", "phone", "CA_PHONE", false,
                false,
                new string[] { "phone", "mobile", "cell", "tel" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("ca_postal_code", "CA", "postcode",
                @"\b[A-Za-z]\d[A-Za-z][ \t-]?\d[A-Za-z]\d\b",
                "[CA_POSTAL_REDACTED]", "postal_code", "CA_POSTAL", false,
                false,
                new string[] { "postal", "zip", "post code", "mailing" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("ca_passport", "CA", "passport",
                @"\b[A-Za-z]{2}\d{6}\b",
                "[CA_PASSPORT_REDACTED]", "passport", "CA_PASSPORT", true,
                false,
                new string[] { "passport", "travel document", "citizenship" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("za_id_number", "ZA", "national_id",
                @"\b(\d{2})(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])(\d{4})(0|1)(\d{2})\b",
                "[ZA_ID_REDACTED]", "za_id_number", "ZA_ID", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] { "sa id", "rsa id", "south african id", "suid-afrikaanse id", "id no", "id-nommer", "home affairs" },
                true, "za_id", true),
            new("za_phone", "ZA", "phone",
                @"(?:\+27[ \t]?|\b0)[6-8]\d[ \t]?\d{3}[ \t]?\d{4}\b",
                "[PHONE_REDACTED]", "za_phone", "PHONE", false,
                false,
                new string[] {  },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("gh_ghana_card", "GH", "national_id",
                @"\b[A-Z]{3}-\d{8,9}-[0-9A-Z]\b",
                "[GHANA_CARD_REDACTED]", "gh_ghana_card", "GHANA_CARD", true,
                false,
                new string[] { "ghana card", "ghanacard", "ghana revenue", "nia pin", "personal id number", "gra tin" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("it_codice_fiscale", "IT", "tax_id",
                @"\b[A-Z]{6}\d{2}[ABCDEHLMPRST]\d{2}[A-Z]\d{3}[A-Z]\b",
                "[CODICE_FISCALE_REDACTED]", "it_codice_fiscale", "CODICE_FISCALE", true,
                false,
                new string[] { "codice fiscale", "cod. fisc", "cod.fisc", "c.f.", "anagrafe tributaria", "tessera sanitaria" },
                new string[] {  },
                new string[] {  },
                true, "it_codice_fiscale", true),
            new("ke_kra_pin", "KE", "tax_id",
                @"\b[AP]\d{9}[A-Z]\b",
                "[KRA_PIN_REDACTED]", "ke_kra_pin", "KRA_PIN", true,
                false,
                new string[] { "kra pin", "kra", "tax pin", "itax", "pin certificate", "personal identification number" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("mu_tan", "MU", "tax_id",
                @"\b[123578]\d{7}\b",
                "[TAN_REDACTED]", "mu_tan", "TAN", true,
                false,
                new string[] { "tax account number", "mauritius revenue", "tan ", "tan:", "tan no", "tan number", "mra tan" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("mx_rfc", "MX", "tax_id",
                @"\b[A-Z]{4}\d{6}[A-Z0-9]{3}\b",
                "[RFC_REDACTED]", "mx_rfc", "RFC", true,
                false,
                new string[] { "rfc", "homoclave", "registro federal de contribuyentes", "contribuyentes", "constancia de situación fiscal" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("my_mykad", "MY", "national_id",
                @"\b\d{6}-?\d{2}-?\d{4}\b",
                "[MYKAD_REDACTED]", "my_mykad", "MYKAD", true,
                false,
                new string[] { "mykad", "my kad", "kad pengenalan", "no. kad pengenalan", "nric", "ic number", "no. ic", "mykid" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("pk_cnic", "PK", "national_id",
                @"\b\d{5}-?\d{7}-?\d\b",
                "[CNIC_REDACTED]", "pk_cnic", "CNIC", true,
                false,
                new string[] { "cnic", "nadra", "nic number", "identity card number", "شناختی کارڈ", "شناختی" },
                new string[] {  },
                new string[] {  },
                false, null, false),
            new("sg_nric", "SG", "national_id",
                @"\b[STFGM]\d{7}[A-Z]\b",
                "[NRIC_REDACTED]", "sg_nric", "NRIC", true,
                false,
                new string[] { "nric", "fin number", "fin no", "fin:", "identity card", "identification number", "cpf", "singpass" },
                new string[] {  },
                new string[] {  },
                true, "sg_nric", true),
            new("th_national_id", "TH", "national_id",
                @"\b\d-?\d{4}-?\d{5}-?\d{2}-?\d\b",
                "[NATIONAL_ID_REDACTED]", "th_national_id", "NATIONAL_ID", true,
                false,
                new string[] { "national id", "thai id", "เลขประจำตัวประชาชน", "บัตรประชาชน", "เลขบัตร", "promptpay" },
                new string[] {  },
                new string[] {  },
                true, "th_national_id", true),
            new("id_nik", "ID", "national_id",
                @"\b\d{16}\b",
                "[NIK_REDACTED]", "id_nik", "NIK", true,
                false,
                new string[] { "nomor induk kependudukan", "kartu tanda penduduk", "dukcapil" },
                new string[] { "nik", "e-ktp", "ektp", "ktp", "npwp" },
                new string[] {  },
                false, null, false),
        };

        // Signals is in evaluation order. Stop at the first signal a country matches.
        public static readonly IReadOnlyList<PiiSignal> Signals = new PiiSignal[]
        {
            new("AU",
                @"\b\d{3}\s\d{3}\s\d{3}\b",
                "",
                new string[] { "tfn", "tax file", "medicare" },
                new string[] {  },
                "AU"),
            new("AU",
                @"\b\d{4}\s\d{5}\s\d{1}\b",
                "",
                new string[] {  },
                new string[] {  },
                "AU"),
            new("AU",
                @"\b(0[2-9]|\+61)\d{8,9}\b",
                "",
                new string[] { "au", "australia", "australian" },
                new string[] {  },
                "AU"),
            new("GB",
                @"\b[A-Z]{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?\d{2}[ \t]?[A-D]\b",
                "i",
                new string[] { "national insurance", "ni number", "nino", "ni:" },
                new string[] {  },
                "GB"),
            new("GB",
                @"\b[A-Z]{1,2}\d{1,2}[ \t]?\d[A-Z]{2}\b",
                "",
                new string[] { "uk", "united kingdom", "britain", "postcode" },
                new string[] {  },
                "GB"),
            new("GB",
                @"\b(\+44|0044)\d{10}\b",
                "",
                new string[] { "uk", "united kingdom", "britain" },
                new string[] {  },
                "GB"),
            new("CA",
                @"\b\d{3}[- \t]\d{3}[- \t]\d{3}\b",
                "",
                new string[] { "sin", "social insurance", "canada revenue", "cra", "employment insurance" },
                new string[] {  },
                "CA"),
            new("CA",
                @"\b[A-Za-z]\d[A-Za-z][ \t]?\d[A-Za-z]\d\b",
                "",
                new string[] { "canada", "canadian", "postal code", "province" },
                new string[] {  },
                "CA"),
            new("ZA",
                @"\b\d{13}\b",
                "",
                new string[] { "id number", "identity number", "south africa", "sa id", "rsa", "popia", "fica" },
                new string[] {  },
                "ZA"),
            new("ZA",
                @"\b(\+27|0)[6-8]\d{8}\b",
                "",
                new string[] { "south africa", "za", "johannesburg", "cape town", "durban", "pretoria" },
                new string[] {  },
                "ZA"),
            new("DE",
                @"\b[1-9]\d{10}\b",
                "",
                new string[] { "steuer", "steuernummer", "finanzamt", "tax id", "german" },
                new string[] {  },
                "DE"),
            new("DE",
                @"\b(\+49|0049)\d{10,11}\b",
                "",
                new string[] { "germany", "german", "deutschland", "de" },
                new string[] {  },
                "DE"),
            new("NG",
                @"\b\d{11}\b",
                "",
                new string[] { "bvn", "nin", "bank verification", "nigeria", "nigerian" },
                new string[] {  },
                "NG"),
            new("NG",
                @"\b(\+234|0)[7-9]\d{9}\b",
                "",
                new string[] { "nigeria", "nigerian", "lagos", "abuja" },
                new string[] {  },
                "NG"),
            new("AE",
                @"\b784[- \t]\d{4}[- \t]\d{7}[- \t]\d{1}\b",
                "",
                new string[] {  },
                new string[] {  },
                "AE"),
            new("AE",
                @"\b(\+971|00971)\d{9}\b",
                "",
                new string[] { "uae", "emirates", "dubai", "abu dhabi" },
                new string[] {  },
                "AE"),
            new("IN",
                @"\b[A-Z]{5}\d{4}[A-Z]{1}\b",
                "",
                new string[] {  },
                new string[] {  },
                "IN"),
            new("IN",
                @"\b\d{4}\s\d{4}\s\d{4}\b",
                "",
                new string[] { "aadhaar", "aadhar", "india", "indian" },
                new string[] {  },
                "IN"),
            new("SA",
                @"\b1\d{9}\b",
                "",
                new string[] { "saudi", "ksa", "riyadh", "national id", "iqama" },
                new string[] {  },
                "SA"),
            new("SA",
                @"\b(\+966|00966)\d{9}\b",
                "",
                new string[] { "saudi", "ksa", "riyadh" },
                new string[] {  },
                "SA"),
            new("BR",
                @"\b\d{3}\.\d{3}\.\d{3}-\d{2}\b",
                "",
                new string[] { "cpf", "brazil", "brasil", "brazilian" },
                new string[] {  },
                "BR"),
            new("BR",
                @"\b(\+55|0055)\d{11}\b",
                "",
                new string[] { "brazil", "brasil" },
                new string[] {  },
                "BR"),
            new("JP",
                @"\b\d{4}[ \t]?\d{4}[ \t]?\d{4}\b",
                "",
                new string[] { "my number", "individual number", "マイナンバー", "個人番号", "japan", "japanese", "日本", "tokyo", "osaka", "nagoya", "yokohama" },
                new string[] {  },
                "JP"),
            new("JP",
                @"\b(\+81|0081)[ \t]?\d{1,4}[ \t-]?\d{2,4}[ \t-]?\d{4}\b",
                "",
                new string[] { "japan", "japanese", "日本", "tokyo", "osaka" },
                new string[] {  },
                "JP"),
            new("CN",
                @"\b\d{17}[0-9Xx]\b",
                "",
                new string[] { "resident id", "resident identity", "identity card", "id card", "身份证", "身份證", "居民身份证", "china", "chinese", "prc", "beijing", "shanghai", "shenzhen", "guangzhou" },
                new string[] {  },
                "CN"),
            new("CN",
                @"\b(\+86|0086)[ \t]?1[3-9]\d{9}\b",
                "",
                new string[] { "china", "chinese", "prc", "beijing", "shanghai", "shenzhen", "guangzhou" },
                new string[] {  },
                "CN"),
            new("KR",
                @"\b\d{6}-?[1-8]\d{6}\b",
                "",
                new string[] { "resident registration", "resident number", "rrn", "jumin", "주민등록번호", "주민번호", "korea", "korean", "seoul", "busan", "incheon" },
                new string[] {  },
                "KR"),
            new("KR",
                @"\b(\+82|0082)[ \t]?1[016789][ \t-]?\d{3,4}[ \t-]?\d{4}\b",
                "",
                new string[] { "korea", "korean", "seoul", "busan", "incheon" },
                new string[] {  },
                "KR"),
            new("GH",
                @"\b[A-Z]{3}-\d{8,9}-[0-9A-Z]\b",
                "",
                new string[] { "ghana card", "ghanacard", "ghana", "accra", "kumasi", "nia pin", "gra tin" },
                new string[] {  },
                "GH"),
            new("GH",
                @"\b(\+233|00233)[ \t]?\d{9}\b",
                "",
                new string[] { "ghana", "ghanaian", "accra", "kumasi", "tema" },
                new string[] {  },
                "GH"),
            new("IT",
                @"\b[A-Z]{6}\d{2}[ABCDEHLMPRST]\d{2}[A-Z]\d{3}[A-Z]\b",
                "",
                new string[] { "codice fiscale", "cod. fisc", "c.f.", "anagrafe tributaria", "italy", "italia", "italian", "italiana", "roma", "milano", "napoli", "torino" },
                new string[] {  },
                "IT"),
            new("IT",
                @"\b(\+39|0039)[ \t]?\d{9,11}\b",
                "",
                new string[] { "italy", "italia", "italian", "italiana", "roma", "milano", "napoli", "torino" },
                new string[] {  },
                "IT"),
            new("KE",
                @"\b[AP]\d{9}[A-Z]\b",
                "",
                new string[] { "kra", "itax", "tax pin", "kenya", "kenyan", "nairobi", "mombasa", "kisumu" },
                new string[] {  },
                "KE"),
            new("KE",
                @"\b(\+254|00254)[ \t]?\d{9}\b",
                "",
                new string[] { "kenya", "kenyan", "nairobi", "mombasa", "kisumu" },
                new string[] {  },
                "KE"),
            new("MU",
                @"\b[123578]\d{7}\b",
                "",
                new string[] { "mauritius", "mauritian", "port louis", "mauritius revenue", "mra tan" },
                new string[] {  },
                "MU"),
            new("MU",
                @"\b(\+230|00230)[ \t]?\d{7,8}\b",
                "",
                new string[] { "mauritius", "mauritian", "port louis" },
                new string[] {  },
                "MU"),
            new("MX",
                @"\b[A-Z]{4}\d{6}[A-Z0-9]{3}\b",
                "",
                new string[] { "rfc", "homoclave", "contribuyentes", "mexico", "méxico", "mexican", "mexicano", "cdmx", "guadalajara", "monterrey" },
                new string[] {  },
                "MX"),
            new("MX",
                @"\b(\+52|0052)[ \t]?\d{10}\b",
                "",
                new string[] { "mexico", "méxico", "mexican", "mexicano", "cdmx", "guadalajara", "monterrey" },
                new string[] {  },
                "MX"),
            new("MY",
                @"\b\d{6}-\d{2}-\d{4}\b",
                "",
                new string[] { "mykad", "kad pengenalan", "nric", "malaysia", "malaysian", "kuala lumpur", "johor", "penang", "putrajaya", "selangor" },
                new string[] {  },
                "MY"),
            new("MY",
                @"\b\d{12}\b",
                "",
                new string[] { "mykad", "my kad", "kad pengenalan", "mykid" },
                new string[] {  },
                "MY"),
            new("MY",
                @"\b(\+60|0060)[ \t]?\d{9,10}\b",
                "",
                new string[] { "malaysia", "malaysian", "kuala lumpur", "johor", "penang" },
                new string[] {  },
                "MY"),
            new("PK",
                @"\b\d{5}-\d{7}-\d\b",
                "",
                new string[] { "cnic", "nadra", "pakistan", "pakistani", "karachi", "lahore", "islamabad", "rawalpindi", "شناختی" },
                new string[] {  },
                "PK"),
            new("PK",
                @"\b\d{13}\b",
                "",
                new string[] { "cnic", "nadra", "شناختی" },
                new string[] {  },
                "PK"),
            new("PK",
                @"\b(\+92|0092)[ \t]?3\d{9}\b",
                "",
                new string[] { "pakistan", "pakistani", "karachi", "lahore", "islamabad" },
                new string[] {  },
                "PK"),
            new("SG",
                @"\b[STFGM]\d{7}[A-Z]\b",
                "",
                new string[] { "nric", "singpass", "cpf", "iras", "singapore", "singaporean" },
                new string[] {  },
                "SG"),
            new("SG",
                @"\b(\+65|0065)[ \t]?[689]\d{3}[ \t]?\d{4}\b",
                "",
                new string[] { "singapore", "singaporean" },
                new string[] {  },
                "SG"),
            new("TH",
                @"\b\d-\d{4}-\d{5}-\d{2}-\d\b",
                "",
                new string[] { "national id", "thai", "thailand", "เลขประจำตัวประชาชน", "บัตรประชาชน", "bangkok", "promptpay" },
                new string[] {  },
                "TH"),
            new("TH",
                @"\b\d{13}\b",
                "",
                new string[] { "thai id", "thailand", "เลขประจำตัวประชาชน", "บัตรประชาชน", "promptpay" },
                new string[] {  },
                "TH"),
            new("TH",
                @"\b(\+66|0066)[ \t]?\d{9}\b",
                "",
                new string[] { "thailand", "thai", "bangkok", "phuket", "chiang mai" },
                new string[] {  },
                "TH"),
            new("ID",
                @"\b\d{16}\b",
                "",
                new string[] { "nomor induk kependudukan", "kartu tanda penduduk", "dukcapil" },
                new string[] { "nik", "e-ktp", "ektp", "ktp", "npwp" },
                "ID"),
            new("ID",
                @"\b(\+62|0062)[ \t]?\d{9,12}\b",
                "",
                new string[] { "indonesia", "indonesian", "jakarta", "surabaya", "bandung", "medan", "bali" },
                new string[] {  },
                "ID"),
        };
    }
}
